#+TITLE: Readme
#+AUTHOR: Kostas Zorbadelos (kzorba AT nixly DOT net)

* bgp-te-tool: A tool to automate BGP Traffic Engineering in ISPs
** Description
A demonstration of a BGP TE tool in a lab topology using Juniper vMX routers.

The tool utilizes Netbox (IPAM to contain announcement prefixes) and peering-manager (for eBGP Internet peerings) as sources of truth. These systems contain our intended announcements, their policy and all the BGP peerings with the various peers.

The announcement prefixes are tagged with large communities (rfc 8092) indicating the intended policy. The design of the system was inspired by [[https://datatracker.ietf.org/doc/html/rfc8195][Use of BGP Large Communities]]. The configuration is generated and pushed on the routers via [[https://saltproject.io/][Salt]]/[[https://github.com/napalm-automation/napalm][NAPALM]]. The current implementation supports Juniper/JUNOS devices and is demonstrated on a specific network architecture (IP/MPLS core with L3VPNs and Internet service on a dedicated VRF).

The tool ideas hopefully are general enough to be able to be implemented in other vendors and  network architectures as needed.

The full documentation of the tool if currently a work in progress.
